#pragma once

#define SPI_CMD_NEXT_MOTOR 0x10

#define SPI_CMD_SET_SPEED_BASE 0x1A
#define SPI_CMD_SET_POSITION_BASE 0x1B
#define SPI_CMD_COAST 0x30
#define SPI_CMD_BRAKE 0x40
#define SPI_CMD_SET_PID 0x50
#define SPI_CMD_SET_RGB_VALUE 0x51
#define SPI_CMD_REL_ESTOP 0x69
#define SPI_CMD_SET_HOSTNAME 0x70
